using System;
using System.Collections.Generic;
using System.Windows.Forms;
using YourNamespace;

namespace draft3
{
    public partial class Events : Form
    {
        public Events()
        {
            InitializeComponent(); // Initialize the form and its components
            LoadData(); // Load data into the ListBox when the form is opened
        }

        /// <summary>
        /// Fetches data from the database and populates the ListBox.
        /// </summary>
        private void LoadData()
        {
            try
            {
                // SQL query to select data from the Events table
                string query = "SELECT [Event name] FROM Events"; // Ensure column name is enclosed in square brackets

                // Fetch data using the DatabaseHelper
                List<string> data = DatabaseHelper.GetData(query, "Event name");

                // Clear the ListBox to avoid duplicate entries
                listBox1.Items.Clear();

                // Populate the ListBox with data
                foreach (string item in data)
                {
                    listBox1.Items.Add(item);
                }

                // Notify if no data was found
                if (data.Count == 0)
                {
                    MessageBox.Show("No events found.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            catch (Exception ex)
            {
                // Display any errors that occur during the data retrieval
                MessageBox.Show($"An error occurred while loading data: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void Events_Load(object sender, EventArgs e)
        {
            // Optionally, you can move or remove this autogenerated code
            try
            {
                this.eventsTableAdapter.Fill(this.togetherCultureDataSet.Events);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error loading data from DataSet: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void listBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            // Handle selection change in the ListBox if needed
            string selectedEvent = listBox1.SelectedItem?.ToString();
            if (!string.IsNullOrEmpty(selectedEvent))
            {
                MessageBox.Show($"You selected: {selectedEvent}", "Selection", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            // Optional: Handle clicks on DataGridView cells if used
        }
    }
}
